/*
 *
 * Login constants
 *
 */
export const DEFAULT_ACTION = 'app/Login/DEFAULT_ACTION';
export const CHANGE_USERNAME = 'app/Login/CHANGE_USERNAME';
export const CHANGE_USERNAME_SUCCESS = 'app/Login/CHANGE_USERNAME_SUCCESS';
export const SEND_OTP_REQUEST = 'app/Login/SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'app/Login/SEND_OTP_SUCCESS';
export const SEND_OTP_FAILURE = 'app/Login/SEND_OTP_FAILURE';
export const ENABLE_LOGIN_VIEW = 'app/Login/ENABLE_LOGIN_VIEW';
export const LOGIN_WITH_OTP = 'app/Login/LOGIN_WITH_OTP';
export const LOGIN_WITH_OTP_SUCCESS = 'app/Login/LOGIN_WITH_OTP_SUCCESS';
export const LOGIN_WITH_OTP_SUCCESS_PASSWORD = 'app/Login/LOGIN_WITH_OTP_SUCCESS_PASSWORD';
export const LOGIN_WITH_PASSWORD = 'app/Login/LOGIN_WITH_PASSWORD';
export const LOGIN_WITH_PASSWORD_SUCCESS = 'app/Login/LOGIN_WITH_PASSWORD_SUCCESS';
export const LOGIN_WITH_OTP_FAILURE = 'app/Login/LOGIN_WITH_OTP_FAILURE';
export const RESPONCE_MSG = 'app/Login/RESPONCE_MSG';
export const CLOSE_MSG_BAR = 'app/Login/CLOSE_MSG_BAR';
export const FORGOT_PASSWORD = 'app/Login/FORGOT_PASSWORD';
export const FORGOT_PASSWORD_PHONE = 'app/Login/FORGOT_PASSWORD_PHONE';
export const FORGOT_PASSWORD_SUCCESS = 'app/Login/FORGOT_PASSWORD_SUCCESS';
export const DIRECT_MSG = 'app/Login/DIRECT_MSG';
export const FORGOT_PASSWORD_PHONE_SUCCESS = 'app/Login/FORGOT_PASSWORD_PHONE_SUCCESS';
export const SAVE_LOGIN_DATA = 'app/Login/SAVE_LOGIN_DATA';
export const NEW_PASSWORD = 'app/Login/NEW_PASSWORD';
export const NEW_PASSWORD_FOR_REACT = 'app/Login/NEW_PASSWORD_FOR_REACT';
export const NEW_PASSWORD_ACTION_REACT = 'app/Login/NEW_PASSWORD_ACTION_REACT';
export const LOGIN_WITH_PASSWORD_SUCCESS1 = 'app/Login/LOGIN_WITH_PASSWORD_SUCCESS1';
export const PASSWORD_RESPONSE = 'app/Login/PASSWORD_RESPONSE';
export const SEND_OTP_REQUEST_PSWD = 'app/Login/SEND_OTP_REQUEST_PSWD';
export const SEND_OTP_SUCCESS_PSWD = 'app/Login/SEND_OTP_SUCCESS_PSWD';
export const USER_REGISTRATION_USING_GMAIL = 'app/Login/USER_REGISTRATION_USING_GMAIL';
export const USER_SUCCESS_REGISTRATION_USING_GMAIL = 'app/Login/USER_SUCCESS_REGISTRATION_USING_GMAIL';
export const GET_CUST_ID_BY_EMAIL = 'app/Login/GET_CUST_ID_BY_EMAIL'
export const GET_CUST_ID_BY_EMAIL_SUCCESS = 'app/Login/GET_CUST_ID_BY_EMAIL_SUCCESS'
