/*
 * AppConstants
 * Each action has a corresponding type, which the reducer knows and picks up on.
 * To avoid weird typos between the reducer and the actions, we save them as
 * constants here. We prefix them with 'yourproject/YourComponent' so we avoid
 * reducers accidentally picking up actions they shouldn't.
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'yourproject/YourContainer/YOUR_ACTION_CONSTANT';
 */
export const LOAD_REPOS = 'boilerplate/App/LOAD_REPOS';
export const LOAD_REPOS_SUCCESS = 'boilerplate/App/LOAD_REPOS_SUCCESS';
export const LOAD_REPOS_ERROR = 'boilerplate/App/LOAD_REPOS_ERROR';
export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const Constants = {
  enviroment: 'production',
  urls: {
    production: 'https://productionapi.adibuja.com',
    development: 'https://devuiapi.adibuja.com',
    testing: '',
    live: 'https://api.adibuja.com',
    // baseUrl: 'https://devuiapi.adibuja.com',
    baseUrl: 'https://demoliveuiapi.adibuja.com',
    // baseUrl: 'https://api.adibuja.com',
    altBaseUrl: '',
    responsibleUrl: '',
    productionui: 'https://api.adibuja.com',
  },
  // urls: {
  //   production: 'https://productionui.adibuja.com',
  //   development: '',
  //   testing: '',
  //   baseUrl: 'https://productionapi.adibuja.com',
  //   altBaseUrl: '',
  //   responsibleUrl: '',
  //   productionui: 'https://productionui.adibuja.com',
  // },
  authKey: '',
  endPoints: {
    Client: '/api/v1/client',
    clientaddress: '/api/v1/clientaddress?',
    ClientByClientId: '/api/v1/ClientByClientId?',
    MegaMainMenu: '/api/v1/MegaMainMenu?',
    Billboard: '/api/v1/billboards?',
    Billboardid: '/api/v1/billboard/{id}?',
    DealoftheDay: '/api/v2/getDealOfTheDayProducts?',
    DealoftheDayPage: '/api/v3/getDealOfTheDayProductsWithPagination?',
    token: '/token',
    // topsellingai: '/api/v2/AIGetTopSellingProductListAllForreact?',
    topsellingai: '/api/v2/AIGetTopSellingProductList?',
    topsellingdb: '/api/v3/getTopSellingProductList?',
    banners: '/api/v1/AdvertisementDetails?',
    Advertisement: '/api/v1/AdvertisementDetails?',
    ShopByCategory: '/api/v1/get-homepage-subcategories?',
    BrandList: '/api/v1/getBrandListForReact?',
    RecentlyPurchasedOrders: '/api/v2/get-recentlypurchasedproducts-by-customer?',
    FooterMegaMainMenu: '/api/v1/MegaMainMenu?',
    footer: '/api/v1/staticwebpage?',
    footerMiddle: '/api/v1/staticwebpagesection?',
    GetCustIdByEmail: '/api/v1/customer/GetCustIdByEmail?',
    getcustomerbyphone: '/api/v1/customer/get-customer-by-phone?',
    getcustomerbyguid: '/api/v1/customer/GetAllCustomerIdByGuid?',
    sendsms: '/api/v1/send-sms',
    generateotpforregistration: '/api/v1/customer/generate-otp-for-registration?',
    getsmstemplate: '/api/v1/get-smstemplate?',
    verifyregistrationotp: '/api/v1/customer/verify-registration-otp?',
    getverifiedemailphoneforregistration: '/api/v1/customer/get-verified-email-phone-for-registration',
    uiotpmail: '/api/v1/ui-otp-mail?',
    register: '/api/v1/customer/register',
    shortnenurl: 'api/v1/shortnen-url?',
    updateCart: '/api/v1/updateCart?',
    getShoppingCartList: '/api/v1/getShoppingCartList?',
    RemoveFromCart: '/api/v1/RemoveFromCart?',
    getCartCommon: '/api/v1/get-cart-common?',
    couponCodeList: '/api/v1/get-couponcodelist?',
    applyCoupenCommon: '/api/v1/apply-coupon-common?',
    generatemobileotp: '/api/v1/customer/generate-mobile-otp?',
    verifyotpnumber: '/api/v1/customer/verify-otp-number?',
    generateotp: 'customer/generate-otp,',
    verifyotp: ' customer/verify-otp',
    skulisting: '/api/v3/skulisting?',
    generateotpforregistrationnew: '/api/v2/generate-otp-for-registration?',
    GoogleApi: '/api/v1/get-google-places-api-and-default-delivery-locality-details',
    autocomplete: '/api/v1/get-google-places-predictions-ForReact?',
    placedetails: '/api/v1/get-google-place-details-ForReact?',
    geocode: 'https://maps.googleapis.com/maps/api/geocode/json?',
    // checkserviceavailability: 'https://productionapi.adibuja.com/api/v1/check-service-availability?', // for production 
    // for demo live
    checkserviceavailability: 'https://demoliveuiapi.adibuja.com/api/v1/check-service-availability?',
    // For live
    // checkserviceavailability: 'https://api.adibuja.com/api/v1/check-service-availability?',
    updateaddress: '/api/v1/update-address?',
    customeraddress: '/api/v1/customeraddress?',
    defaultaddress: '/api/v1/defaultaddress?',
    gettomorrowsdeliveryslot: '/api/v1/get-tomorrows-delivery-slot',
    getdayAftertomorrowsdeliveryslot: '/api/v1/get-dayAftertomorrows-delivery-slot',
    Cartnew: '/api/v1/Cartnew?',
    initiatetransaction: '/api/v1/initiate-transaction?',
    creditcard: '/api/v1/creditcard?',
    UpdateDeliveryDateAndSlotTime: '/api/v1/Update-DeliveryDateAndSlotTime?',
    sendordermail: '/api/v1/send-order-mail?',
    shoppingcartdetails: '/api/v1/get-shoppingcartdetails-by-productAndPriceId?',
    categories: '/api/v1/categories?',
    advancegetskufilter: '/api/v1/advancegetskufilter?',
    searchadvancegetskufilter: '/api/v1/searchadvancegetskufilter?',
    skuFilterlisting: '/api/v2/skuFilterlisting?',
    WishlistcartProductList: '/api/v2/WishlistcartProductList?',
    cancelCouponCode: '/api/v1/cancel-coupon-code?',
    wishlistadd: '/api/v1/wishlist-add?',
    wishlistremoveitem: '/api/v1/wishlist-remove-item?',
    wishlist: '/api/v1/wishlist?',
    sendOtpLogin: '/api/v1/customer/sendOTP?',
    forgotpassword: '/api/v1/customer/forgotpassword?',
    forgotpasswordForPhone: '/ForgotPasswordForReact?',
    verifyLoginOTP: '/api/V2/VerifyLoginUser',
    verifyLoginPassWord: '/api/v1/customer/authenticate',
    SkuV: '/api/v2/sku?',
    Review: '/api/v1/Review?',
    // skurelated: '/api/v2/skurelated?',
    // skurelated: '/api/v3/skurelated?',
    skurelated: '/api/v2/GetSimilarProductList?',
    recentlyview: '/api/v2/get-recently-products-forreact?',
    // RecommendedProducts: '/api/v2/AIGetRecommendedProducts?',
    // RecommendedProducts: '/api/v/AIGetRecommendedProducts?',
    recommendedProductsai: '/api/v2/AIGetRecommendedProductListAllForReact?',
    RazorPaycreateorder: '/api/v1/RazorPay-createorder',
    captureRazorPayorder: '/api/v1/capture-RazorPay-order',
    RazorPayverifysigniture: '/api/v1/RazorPay-verify-signiture',
    customerdetail: '/api/v1/customerdetailnew?',
    // https://api.adibuja.com/api/v1/customerdetailnew?clientid=1&guid=e53162dd-b25d-4731-8c10-f08e55532222
    myorder: '/api/v1/get-orderdetails-for-myorder?',
    orderlisting: '/api/v1/get-customer-all-orders?',
    savcartlisting: '/api/v1/get-customer-saved-cart-grouplist?',
    viewsavecart: '/api/v1/get-customer-saved-cart?',
    savecustomercart: '/api/v1/save-customer-cart?',
    removesavecartlistitem: '/api/v1/remove-customer-saved-cart-grouplist-item?',
    SavedCartCheckout: '/api/v1/SavedCartCheckout?',
    removesavecartlist: '/api/v1/remove-customer-saved-cart-grouplist?',
    notify: '/api/v1/notify-me-on-product-availabile-all?',
    skusfromcodes: '/api/V2/get-skusfromcodes?',
    firsttimepasswordchangedornot: '/api/v1/customer/firsttimepasswordchangedornot?',
    UpdateStatusFirstTimePasswordChanged: '/api/v1/customer/UpdateStatusFirstTimePasswordChanged?',
    changePassword: '/api/v1/customer/ChangePasswordForReact',
    setupPassword: '/api/v1/customer/setup-password',
    Savefeedbackdeliveryreview: '/api/v1/Savefeedbackdeliveryreview',
    Savefeedbackorderreview: '/api/v1/Savefeedbackorderreview',
    CheckReviewIsGivenOrNot: '/api/v1/CheckReviewIsGivenOrNot',
    SaveFeedbackFromPDP: '/api/v1/SaveFeedbackFromPDP',
    GetAllReviewFromCustomerForProduct: '/api/v1/GetAllReviewFromCustomerForProduct',
    GetFeedbackDetailsOrderAndItem: '/api/v1/GetFeedbackDetailsOrderAndItem',
    AIAutosuggestion: '/api/v2/AI/ai-get-skus-for-search-autocomplete?',
    // DBAutosuggestion: '/api/v1/get-skus-for-search-autocomplete?',
    DBAutosuggestion: '/api/v2/get-ai-search-autocomplete-list?',
    skusearchlist: '/api/v2/get-skusearchlist?',
    ReorderProductList: '/api/v3/Get-Customer-Reorder-Product-List?',
    Reorder: '/api/v2/Get-Customer-Reorder-Product-List?',
    wallettransactions: '/api/v1/customer/getcustwallettransactions?',
    cancelorder: '/api/v1/cancel-order',
    refundorder: '/api/v1/refund-order',
    getSellerPDPList: '/api/v2/getSellerPDPList?',
    newslettersubscription: '/api/v1/send-newslettersubscription-emailForReact?',
    GetTrackOrderStatus: '/api/v1/GetTrackOrderStatus',
    GetAllTrackOrderItemStatusDetail: '/api/v1/GetAllTrackOrderItemStatusDetail',
    OrderCancelStatusList: '/api/v1/order/getOrderCancelStatusList?',
    recentorders: '/api/v1/recent-orders?',
    payment: 'https://api.razorpay.com/v1/payments/',
    Updatedeliveryinfosendordersmsemail: '/api/v2/Update-deliveryinfo-send-order-sms-email?',
    paymentdetailbyorder: '/api/v1/payment-detail-by-order?',
    deleteaddress: '/api/v1/delete-address?',
    SendEmailAndSmsForRegistration: '/api/V2/SendEmailAndSmsForRegistration',
    SendEmailOrMobileForRegistration: '/api/v1/add-customer-detail?',
    generateandsendphoneemailchangeotp: '/api/V2/generateandsendphoneemailchangeotp?',
    verifyphoneemailchangeotp: '/api/v1/customer/verify-phone-email-change-otp?',
    getbrandlistproducts: '/api/v2/getbrandlistproducts?',
    getBrandList: '/api/v1/getBrandList?',
    UpdateProfile: '/api/v1/UpdateProfile?',
    sendUpdateProfileEmail: '/api/v1/send-updateprofile-email?',
    getSmsTemplate: '/api/v1/get-smstemplate?',
    sendSMS: '/api/v1/send-sms?',
    recentlyviewd: '/api/v2/get-products-from-ids?',
    AIGetRecommendedProducts: '/api/v3/AIGetRecommendedProducts?',
    WishlistcartProductListforreact: '/api/v2/WishlistcartProductListforreact?',
    NewPassword: '/api/v1/customer/new-password?',
    NewPasswordForReact: '/newpasswordforreact?',
    GetAllTrackOrderStatusDetail: '/api/v1/GetAllTrackOrderStatusDetail',
    SavedcartProductList: '/api/v2/SavedcartProductList?',
    Getskudispplayinsubcategories: '/api/v1/getskudispplayinsubcategories?',
    FAQ: '/api/v1/faqs',
    SetupNewPasswordForReact: '/api/v1/customer/NewPasswordForReact',
    GetTopTrendingProductList: '/api/v2/GetAllTopTrendingProductsList?',
    FeatureProduct: '/api/v2/FeatureProductList?',
    NewArrivalProduct: '/api/v2/NewArrivalProductList?',
    GetChatBotResponse: '/api/v2/ai/chatbot?',
    GetRemoveInactiveFromCart: '/api/v1/RemoveInactiveFromCart?',
    GetCartnew: '/api/v1/Cartnew?',
    GetRelatedCategoryList: '/api/v2/RelatedCategoryList?',
    savecontatinformation: '/api/v2/ContactUs'
  },
  messages: {
    Invalidnumber: 'Please enter valid mobile number (10 digit) or Email.'
  }
};
export default Constants;
// https://devuiapi.adibuja.com/api/v2/Get-Customer-Reorder-Product-List?CustGUID=2c605971-713c-4ec5-b28e-35a436bd5431&LanguageId=2&CartGUID=c6eee012-4b52-49a8-83cc-786e3d6641fe&clientId=1&currencyCode=INR