/*
 *
 * Product constants
 *
 */
export const DEFAULT_ACTION = 'app/Product/DEFAULT_ACTION';
export const GET_SKU_PRODUCTDETAIL = 'app/Product/ GET_SKU_PRODUCTDETAIL';
export const GET_SKU_PRODUCTDETAIL_SUCCESS = 'app/Product/GET_SKU_PRODUCTDETAIL_SUCCESS';
export const GET_SKU_PRODUCTDETAIL_FAILURE = 'app/Product/ GET_SKU_PRODUCTDETAIL_FAILURE';
export const GET_CUSTOMER_REVIEW = 'app/Product/GET_CUSTOMER_REVIEW';
export const GET_CUSTOMER_REVIEW_SUCCESS = 'app/Product/GET_CUSTOMER_REVIEW_SUCCESS';
export const GET_CUSTOMER_REVIEW_FAILURE = 'app/Product/GET_CUSTOMER_REVIEW_FAILURE';
export const GET_OTHER_SELLER = 'app/Product/GET_OTHER_SELLER';
export const GET_OTHER_SELLER_SUCCESS = 'app/Product/GET_OTHER_SELLER_SUCCESS';
export const SHOPPING_CART_DETAILS_BUYPRODUCT = 'app/Product/SHOPPING_CART_DETAILS_BUYPRODUCT';